name: Add NPM Credentials
description: Add NPM credentials to the repository

inputs:
  hugeicons-token:
    description: The Hugeicons token
    required: true

runs:
  using: composite

  steps:
    - name: Add NPM credentials
      shell: bash
      run: |
        echo "@hugeicons-pro:registry=https://npm.hugeicons.com/" > .npmrc
        echo "//npm.hugeicons.com/:_authToken=${{ inputs.hugeicons-token }}" >> .npmrc
