name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}-ci"
  cancel-in-progress: true

jobs:
  typecheck:
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.15
      - name: Add NPM credentials
        uses: ./.github/actions/add-npm-credentials
        with:
          hugeicons-token: ${{ secrets.HUGEICONS_TOKEN }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Remove NPM credentials
        uses: ./.github/actions/remove-npm-credentials
      - name: Copy env example
        shell: bash
        run: find . -type f -name ".env.example" -exec sh -c 'cp "$1" "${1%.*}"' _ {} \;
      - name: Type check
        run: bun run typecheck

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.15
      - name: Add NPM credentials
        uses: ./.github/actions/add-npm-credentials
        with:
          hugeicons-token: ${{ secrets.HUGEICONS_TOKEN }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Remove NPM credentials
        uses: ./.github/actions/remove-npm-credentials
      - name: Copy env example
        shell: bash
        run: find . -type f -name ".env.example" -exec sh -c 'cp "$1" "${1%.*}"' _ {} \;
      - name: Lint
        run: bun run lint
