name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.15
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build:dashboard
        env:
          VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    concurrency: deploy-group
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist
      - name: Get commit message
        id: get_head_commit_title
        run: echo "title=$(git log --format=%B -n 1 HEAD | head -n 1)" >> $GITHUB_OUTPUT
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.3.142
      - run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: "Slack Deploy Start Message"
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ vars.SLACK_DEPLOY_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "*Deployment to prod*"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: ${{ steps.get_head_commit_title.outputs.title }}
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "Author: ${{ github.event.head_commit.author.name }}"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "Workflow run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/>"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "Status: ${{ job.status }}"
